"use client";

import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export default function SurveyViewPage() {

  const params = useParams();
  const router = useRouter();

  const surveyNo = params?.surveyNo;

  const [survey, setSurvey] = useState<any>(null);



  useEffect(() => {

    if (!surveyNo) return;

    async function loadSurvey() {

      const res = await fetch(`/api/getSurveyByNo?surveyNo=${surveyNo}`);
      const data = await res.json();

      // ensure rows exists
      if (!data.rows) {
        data.rows = [];
      }

      setSurvey(data);

    }

    loadSurvey();

  }, [surveyNo]);



  // 📄 Download PDF
  function downloadPDF() {

  const doc = new jsPDF();

  // Company Header
  doc.setFontSize(20);
  doc.text("SHRI SIDDHESHWAR SALES AND SERVICES", 105, 15, { align: "center" });

  doc.setFontSize(14);
  doc.text("Motor & Pump Pipeline Survey Report", 105, 25, { align: "center" });

  doc.setFontSize(12);

  // Survey Info
  doc.text(`Survey No: ${survey.surveyNo}`, 14, 40);
  doc.text(`Customer: ${survey.customer}`, 14, 48);
  doc.text(`Village: ${survey.village}`, 14, 56);
  doc.text(`Discharge: ${survey.discharge || "-"}`, 120, 48);
  doc.text(`Static Height: ${survey.staticHeight || "-"}`, 120, 56);

  const tableRows = survey.rows.map((row:any) => [
    row.description,
    row.size,
    row.qty,
    row.unit,
    row.floss,
    row.remark
  ]);

  autoTable(doc,{
    startY:70,
    head:[["Description","Size","Qty","Unit","F.Loss","Remark"]],
    body:tableRows,
    theme:"grid",
    headStyles:{
      fillColor:[41,128,185]
    }
  });

  const finalY = (doc as any).lastAutoTable.finalY;

  doc.setFontSize(14);
  doc.text(`Total Head: ${survey.totalHead}`, 14, finalY + 15);

  // Footer
  doc.setFontSize(10);
  doc.text("Generated by Pipeline Survey System", 105, 285, { align:"center" });

  doc.save(`survey-${survey.surveyNo}.pdf`);

}



  if (!survey) {
    return <div className="p-6">Loading...</div>;
  }



  return (

    <div className="p-6">

      {/* Top Buttons */}

      <div className="flex gap-3 mb-6">

        <button
          onClick={() => router.push("/dashboard")}
          className="bg-gray-500 text-white px-4 py-2 rounded"
        >
          Back
        </button>

        <button
          onClick={() => router.push(`/survey/edit/${survey.surveyNo}`)}
          className="bg-yellow-500 text-white px-4 py-2 rounded"
        >
          Edit Survey
        </button>

        <button
          onClick={downloadPDF}
          className="bg-green-600 text-white px-4 py-2 rounded"
        >
          Download PDF
        </button>

      </div>



      <h1 className="text-2xl font-bold mb-4">
        Survey #{survey.surveyNo}
      </h1>



      {/* Survey Details */}

      <div className="grid grid-cols-2 gap-4 mb-6">

        <div>
          <b>Customer:</b> {survey.customer || "-"}
        </div>

        <div>
          <b>Village:</b> {survey.village || "-"}
        </div>

        <div>
          <b>Discharge:</b> {survey.discharge || "-"}
        </div>

        <div>
          <b>Static Height:</b> {survey.staticHeight || "-"}
        </div>

      </div>



      {/* Items Table */}

      <table className="w-full border">

        <thead className="bg-gray-100">

          <tr>
            <th className="border p-2">Description</th>
            <th className="border p-2">Size</th>
            <th className="border p-2">Qty</th>
            <th className="border p-2">Unit</th>
            <th className="border p-2">F.Loss</th>
            <th className="border p-2">Remark</th>
          </tr>

        </thead>



        <tbody>

          {survey.rows.length === 0 ? (

            <tr>
              <td colSpan={6} className="text-center p-3">
                No items
              </td>
            </tr>

          ) : (

            survey.rows.map((row:any, i:number) => (

              <tr key={i} className="text-center">

                <td className="border p-2">{row.description}</td>
                <td className="border p-2">{row.size}</td>
                <td className="border p-2">{row.qty}</td>
                <td className="border p-2">{row.unit}</td>
                <td className="border p-2">{row.floss}</td>
                <td className="border p-2">{row.remark}</td>

              </tr>

            ))

          )}

        </tbody>

      </table>



      <div className="mt-4 font-semibold text-lg">
        Total Head: {survey.totalHead || 0}
      </div>

    </div>

  );

}